id: A4C6D4CFC
title: Concise Averting Ritual for the Practice of Hayagrīva and Garuḍa
type: translation
pechas:
- I34629EBB
- I2AC4EFBA
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:44:41.597395
  last_modified_at: 2023-01-04 11:44:41.597400
  collections:
  - Dola Jigme Kalzang Series
  - Works of Tibetan Masters
alignment_to_base:
  I34629EBB/3F83: 7F3C
  I2AC4EFBA/D77B: 7F3C
